theme = "gruvbox"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
