[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
language-servers = ["ruff", "basedpyright"]
auto-format = true
formatter = { command = "sh", args = [
  "-c",
  "uvx ruff check --fix - | uvx ruff format -"
] }
